name: Keep Railway Alist Alive

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟访问一次
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Alist Website
        uses: lannonbr/website-uptime-monitor@master
        with:
          url: "https://alist-production-8dae.up.railway.app/"
